const test=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs');
const M=require('../assets/app-model.js'),J=require('../assets/journey.js'),Solar=require('../assets/solar.js'),W=require('../assets/weather.js'),V=require('../assets/scene.js');
const NOW=Date.parse('2026-09-12T03:00:00Z');
function at(n){const s=M.fresh(NOW);s.visual.journey.earned=n;s.visual.journey.inviteRemainder=n%10;return s;}
for(const n of [0,1,9,10,500,999,1000,1024,1025,1026,1500,2050,3075,512500])test('Circuit boundary '+n,()=>{
 const p=J.progress(at(n));a.equal(p.total,n);a.equal(p.east+p.west+p.markers,p.filled);a.equal(p.laps,Math.floor(n/1025));a.ok(p.flags<=100);a.ok(p.filled<=1025);a.ok(p.east<=500&&p.west<=500&&p.markers<=25);
 if(n===10){a.equal(p.east,10);a.equal(p.west,0);a.equal(p.flags,1);}
 if(n===500){a.equal(p.east,250);a.equal(p.west,250);}
 if(n===1025){a.equal(p.filled,1025);a.equal(p.color,J.COLORS[0]);}
 if(n===1500){a.equal(p.filled,475);a.equal(p.color,J.COLORS[1]);a.equal(p.previousColor,J.COLORS[0]);}
});
test('Imported lifetime achievement is converted once without changing any question record',()=>{const s={m:{'1':{lv:3,cor:40,att:41},'2':{lv:4,cor:2}},gcHit:50};const before=JSON.stringify(s.m);M.ensure(s,NOW);a.equal(J.progress(s).total,42);const after=JSON.stringify(s.m);M.ensure(s,NOW);a.equal(JSON.stringify(s.m),after);a.equal(J.progress(s).total,42);a.equal(s.gcHit,50);a.equal(s.m[1].cor,40);});
test('Same-day equivalent questions do not mint new path credits',()=>{const s=M.fresh(NOW),qs=M.Course.pool(1);M.answer(s,qs[0],true,{now:NOW});M.answer(s,qs[0],true,{now:NOW});a.equal(J.progress(s).total,1);});
test('Only ten new credited correct answers yield a new invitation',()=>{const s=M.fresh(NOW);for(let i=0;i<9;i++)J.earned(s);a.equal(s.gcHit,0);J.earned(s);a.equal(s.gcHit,5);a.equal(M.Core.invite(s,NOW,1),1);a.equal(s.gangchiVisits[0].remainingMs,60000);a.equal(s.gcHit,0);});
test('Legacy invitation units retain their existing value',()=>{const s=M.fresh(NOW);s.gcHit=50;M.ensure(s,NOW);a.equal(M.Core.invite(s,NOW,10),10);a.equal(s.gcHit,0);});
test('Wrong-answer correction and placement do not grow the new path',()=>{const s=M.fresh(NOW),q=M.Course.pool(1)[0];M.answer(s,q,true,{mode:'placement',now:NOW});M.answer(s,q,false,{now:NOW});M.answer(s,q,true,{retry:true,now:NOW});a.equal(J.progress(s).total,0);});
test('Weekly rollover never resets path tiers',()=>{const s=at(1500);M.Core.rollover(s,NOW+8*86400000);a.equal(J.progress(s).total,1500);});
test('Path-protecting backup checks reject loss',()=>{a.throws(()=>J.protects(at(1499),at(1500)));const old=at(1500);delete old.visual.journey;a.throws(()=>J.protects(old,at(1500)));a.doesNotThrow(()=>J.protects(at(1500),at(1500)));});
test('New empty profiles may import old backups',()=>{const raw={m:{'1':{cor:3,lv:1,att:3}}};a.doesNotThrow(()=>M.parseImport(JSON.stringify(M.Core.envelope(raw,'en',NOW)),M.fresh(NOW),NOW));});
for(const bad of [-1,1.2,Infinity,NaN,'1025',Number.MAX_SAFE_INTEGER+1])test('Reject invalid path counter '+String(bad),()=>{const s=at(0);s.visual.journey.earned=bad;a.throws(()=>M.validate(s));});
test('Placement opens on island geography, not an unexplained administrative term',()=>{for(const age of ['14-16','17-19','20+']){const s=M.fresh(NOW);M.selectProfile(s,age,false);const p=M.Course.createPlacement(s.learningProfile);const q=M.Course.pickPlacement(p,'ko',()=>0);a.equal(q.unit,2);}});
test('All edict unit questions carry the new why-Dokdo historical context',()=>{for(const q of M.Course.DATA.questions.filter(q=>q.unit===8)){a.ok(q.ko.context.includes('1900'));a.ok(q.ko.context.includes('\ub3c5\ub3c4'));}});
test('Active English does not contain the reported homophone mistranslations',()=>{const text=JSON.stringify(M.Course.DATA).toLowerCase();a.ok(!text.includes('water pipe'));a.ok(!text.includes('yoo in lighthouse'));});
for(const day of ['2026-03-20','2026-06-21','2026-09-12','2026-12-21'])test('Solar time and smooth night phase '+day,()=>{const noon=Date.parse(day+'T03:00:00Z'),t=Solar.times(noon);a.equal(t.day,day);a.ok(t.dawn<t.sunrise&&t.sunrise<t.solarNoon&&t.solarNoon<t.sunset&&t.sunset<t.dusk);a.ok(Solar.phase(noon).darkness<.1);a.ok(Solar.phase(Date.parse(day+'T14:00:00Z')).darkness>.95);a.ok(t.sunset-t.sunrise>8*3600000&&t.sunset-t.sunrise<16*3600000);});
test('Korean date not device-local date',()=>{a.equal(Solar.times(Date.parse('2026-09-11T16:00:00Z')).day,'2026-09-12');a.equal(Solar.clock(Date.parse('2026-09-12T03:00:00Z')),'12:00');});
test('Preview modes never mutate learning state',()=>{const s=at(1500),raw=JSON.stringify(s);for(const mode of ['auto','day','sunset','night'])Solar.phase(NOW,mode);a.equal(JSON.stringify(s),raw);a.equal(Solar.phase(NOW,'night').darkness,1);});
function weather(){return {latitude:37.25,longitude:131.875,current_units:{time:'unixtime',temperature_2m:'\u00b0C',wind_speed_10m:'m/s'},current:{time:NOW/1000,temperature_2m:20,cloud_cover:80,wind_speed_10m:3,weather_code:61}};}
test('Weather is attributed model output with explicit timestamp',()=>{const w=W.parse(weather(),NOW);a.equal(w.model,true);a.equal(w.kind,'rain');a.equal(w.at,NOW);});
for(const kind of ['units','stale','location','missing','invalid','unknown-code'])test('Weather rejects '+kind,()=>{const w=weather();if(kind==='units')w.current_units.temperature_2m='F';if(kind==='stale')w.current.time-=14400;if(kind==='location')w.latitude=35;if(kind==='missing')w.current=null;if(kind==='invalid')w.current.cloud_cover=NaN;if(kind==='unknown-code')w.current.weather_code=12;a.throws(()=>W.parse(w,NOW));});
test('Unconfirmed service terms never make a request',async()=>{let count=0;const c=new W.Client({enabled:false,now:()=>NOW,fetcher:async()=>{count++;}});await c.refresh();a.equal(count,0);a.equal(c.status,'disabled');});
test('Valid weather caches requests and never transmits learner information',async()=>{let count=0;const c=new W.Client({enabled:true,now:()=>NOW,fetcher:async(url,options)=>{count++;a.equal(options.credentials,'omit');a.ok(!url.includes('name='));return{ok:true,json:async()=>weather()};}});await c.refresh();await c.refresh();a.equal(count,1);a.equal(c.current.kind,'rain');});
test('Weather failures return no fictional sunny weather',async()=>{const c=new W.Client({enabled:true,now:()=>NOW,fetcher:async()=>{throw Error('offline');}});await c.refresh();a.equal(c.current,null);a.equal(c.status,'unavailable');});
test('Expired cached weather is not shown as current',()=>{let now=NOW;const c=new W.Client({now:()=>now});c.data=W.parse(weather(),NOW);now+=4*3600000;a.equal(c.current,null);});
test('All 1,000 route anchors are on the intended island',()=>{for(let island=0;island<2;island++){a.equal(V.ROUTES[island].length,500);for(const p of V.ROUTES[island])a.ok(V.inside(p,[V.ART.west,V.ART.east][island]));}});
test('No fonts are packaged as downloadable binaries',()=>{const root=require('node:path').resolve(__dirname,'..');function walk(p){for(const e of fs.readdirSync(p,{withFileTypes:true})){const f=require('node:path').join(p,e.name);if(e.isDirectory())walk(f);else a.ok(!/\.(woff2?|ttf|otf|ttc)$/i.test(e.name),e.name);}}walk(root);});
